export const categoryList = ["Other", "Restaurant", "Museum", "Bar", "Parc"]
export const cuisineList = ["French", "Japanese", "Italian"]
export const starsNumberList = ["1", "2", "3"]
export const medianPricesList = ["1", "2", "3", "4", "5"]
export const artisticCurrentList = ["Modern", "Impressionism", "Romantic"]
export const priceOrderList = ["free", "1", "2", "3", "4", "5"]
export const parcTypesList = ["Parc floral", "Parc forestier"]
